### ISSUE TITLE
API integration with Reentry

### ISSUE THREAD

**Issue by Aeasala** [Apollo-Simulation-Peripheral-Lab/DSKY#13]

**Comment by Pablo-Ortiz-Lopez** [comment]
State fetching is implemented, only keyboard input left

**Comment by Lukeypookie** [comment]
Investigating emitting chords NASSP. Soon™

**Comment by Lukeypookie** [comment]
Reentry integration with the current library (keysender) is working. Waiting on #28 to clear. To proceed with final edits to reentry.ts

**Comment by Lukeypookie** [comment]
nks configured

**Comment by Lukeypookie** [comment]
nks configured
